# Storage backend selection
# Supported values:
# backend=csv
# backend=postgresql

backend=csv
csv_path=../data/inventory.csv
postgres_host=localhost
postgres_port=5432
postgres_database=smart_inventory
postgres_username=postgres
postgres_password=postgres
